### ISSUE TITLE
read -file <json> : check that file contains an array

### ISSUE THREAD

**Issue by henridf** [juttle/juttle#102]
The documentation states that `read -file filename.json` expects a json array in filename.json. 

I accidentally used it with a file that contained a single json object per line. No surrounding array, not comma separated.  That file was happily parsed and processed, with unexpected results (each object was parsed into multiple points). 

Took me a little tinkering around to figure out what was going on -- it would have been more helpful if I got an error stating that my json file wasn't in the right format.

**Comment by dmajda** [comment]
I can confirm a non-JSON file gets parsed when it shouldn’t but I can’t reproduce the “each object was parsed into multiple points” behavior — each line parses as a single point in current master (2859c537f1adea83f8f0c7cb4daf681f58555140):

```
$ cat data
{ "a": 1, "b": 2 }
{ "c": 3, "d": 4 }
$ bin/juttle -e 'read file -file "data"'
┌──────────┬──────────┬──────────┬──────────┐
│ a        │ b        │ c        │ d        │
├──────────┼──────────┼──────────┼──────────┤
│ 1        │ 2        │          │          │
├──────────┼──────────┼──────────┼──────────┤
│          │          │ 3        │ 4        │
└──────────┴──────────┴──────────┴──────────┘
```

I also tried 0.1.0:

```
$ node_modules/.bin/juttle -e 'read file -file "data" -format "json"'
undefined 'Sink undefined: Ignoring new point key(s) "c,d"'
┌──────────┬──────────┐
│ a        │ b        │
├──────────┼──────────┤
│ 1        │ 2        │
├──────────┼──────────┤
│          │          │
└──────────┴──────────┘
```

@henridf Do you have a test case in hand that reproduces the behavior you saw?

**Comment by henridf** [comment]
I realize now that these are really two separate bugs, but here's an example showing the other behavior:

```
$ cat data.json 
{"a": 1, "b": {"c": 1}}
```

```
$ juttle -e "read file -file './data.json' | view text"
[2016-01-06 09:53:52.651] [INFO] juttle-adapter - loaded elastic
[2016-01-06 09:53:53.112] [INFO] juttle-adapter - loaded sqlite
[
{"c":1},
{"a":1,"b":{"c":1}}
]
```

**Comment by dmajda** [comment]
Thanks! I’ll keep this as one issue for now as I suppose adding the check will resolve both problems.

**Comment by dmehra** [comment]
@rlgomes can you take a look at this? `read file` got some enhancements in the last month, is this perhaps resolved?

**Comment by rlgomes** [comment]
closing as this is no longer an issue and covered by nested field/array tests [here](https://github.com/juttle/juttle/blob/master/test/adapters/parsers/json.spec.js)
