### ISSUE TITLE
http read -listen

### ISSUE THREAD

**Issue by mnibecker** [juttle/juttle#111]
_Wouldn't it be great if you could use to power of juttle to set up an http service and write incoming points to your favorite storage backend?_

Proposing listen mode for the builtin `read http` adapter. A simple program would look something like this:

```
read http -listen 2000
| write elastic
```

With this program now running, we can now do a `POST` request to `localhost:2000`:

```
customer_id, product_id, price
12, 1209, 3.00
1, 1400, 5.00
```

### Revised `read http` options:

I'm proposing renaming the `-url` option to `-fetch`. The `-listen` option takes a port number. Either the `-fetch` option or `-listen` option must be specified. If both are specified an error is thrown.

If `-listen` is specified on the `-method` and `-timeField` options will apply. All other fields applicable to `-fetch` will be ignored.

Parameter         |             Description          | Required?
----------------- | -------------------------------- | ---------:
`-fetch`            | URL to issue the HTTP request at |  Yes: either `fetch` or `listen` must be specified 
`-listen` | Port for http endpoint to listen on | Yes: either `fetch` or `listen` must be specified 
`-method`         | HTTP method to use               | No; `-fetch` default: `GET`; `listen` default: `POST`
`-headers`        | headers to attach to the HTTP request in the form `{ key1: "value1", ..., keyN: "valueN" }` | No; default: `{}`
`-body`           | body to send with the HTTP requests | No; default: `{}`
`-timeField`      | The name of the field to use as the time field <br><br>The specified field will be renamed to `time` in the body of the HTTP request. If the points already contain a field called `time`, that field is overwritten. This is useful when the source data contains a time field whose values are not valid time stamps.  | No; defaults to keeping the `time` field as is
`-includeHeaders` | When set to true the headers from the response are appended to each of the points in the response | No; default: `false`

### Content Types

Just like `read http -fetch`, `read http -listen` accepts `text/csv` and `application/json` `content-type` headers. Requests without a `content-type` header or with a different `content-type` value will recieve a `400` bad request response.

#### JSON

JSON requests will be parsed in the same fashion as `read http` fetch. Any serialization errors will be returned as a `400 BAD REQUEST`

#### CSV

Each CSV request needs to have a header row with the keys for the following points.

### Implementation Details

I'd like to use the node stdlib to create the server, using `require('http')` as opposed to 3rd party libraries like express. The goal would be to minimize dependencies.

**Comment by rlgomes** [comment]
+1 further discussion on gitter.
