### ISSUE TITLE
split up JuttleMoment

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#117]
Currently, the `JuttleMoment` class serves several purposes. It contains static functions that implement operations on moments and durations, but it can also be used to wrap either a moment.js moment or a moment.js duration.

This means that determining the actual type of one of these objects requires first checking that the object is an `instanceof JuttleMoment` and then checking whether it contains either a `moment` or a `duration` field to determine what its actual type is.

It would improve the code quality if `JuttleMoment` were refactored to split out the static functions into a `TimeOperations` or analogous module that implements the operations logic on moments and durations.

Then we would create a `JuttleDuration` class as an analog of `JuttleMoment`. This would always wrap a moment.js duration, and the remaining `JuttleMoment` class would always wrap a moment.js moment. This would simplify `instanceof` queries and remove a bunch of the conditional logic from things like valueOf(), etc

Another option would be to avoid creating a wrapper object altogether for moments or durations. Moments would be represented as a moment.js moment or maybe even a Javascript Date. The latter would be easier to work with for adapters and when sending data to client-side views but would be more complicated to implement the time operations. Durations would still be implemented as moment.js durations.

**Comment by davidvgalbraith** [comment]
Same as https://github.com/juttle/juttle/issues/109.
