### ISSUE TITLE
Get rid of `pname` and `juttle` arguments of `Juttle.proc.base#initialize`

### ISSUE THREAD

**Issue by mstemm** [juttle/juttle#132]
While going through the gmail adapter docs, I noticed that I didn't know what the ``pname`` and ``juttle`` arguments to
```
initialize: function(options, params, pname, location, program, juttle) {...}
```
are for.

Can you provide a description or if they are not needed remove them? That makes the API for new adapter writers a bit cleaner.

**Comment by dmajda** [comment]
It looks like `pname` is used only in `Program#get_stats`, which is dead code. I don’t think it makes sense to preserve it, it is not a very good API anyway (I don’t like the idea of carrying pnames over to the runtime, I think stats for given node should be obtained by getting a reference to that node directly and querying the `stats` property). I’ll get rid of it and kill `pname` with it.

As for `juttle`, it is completely unused. Again, I’ll get rid of it.

Note that getting rid of `pname` will require adapting the adapters (getting rid of `juttle` will not as it is the last argument).
