### ISSUE TITLE
Make installation of the Juttle bundle easier

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#136]
Right now, installing the whole Juttle bundle (Juttle + JuttleViz + backends + Outrigger) is hard because `outrigger` has `juttle` only as `peerDependency`, which means it must be installed manually on its side (in npm 3.x). Similarly for backends, which are not listed in `outrigger`’s `package.json` at all. It would be more convenient for users to be able to install the whole thing as one package using one `npm` command.

There are two main options:

  1. Create a meta-package (e.g. `outrigger-assembly`) which would have `juttle` + `jutttle-adapter-*` + `outrigger` as dependencies. The `outrigger` package itself would stay as it is now.

  2. Make `outrigger` require `juttle` and `juttle-adapter-*` as hard dependencies.

The advantage of 2. is simplicity (no additional package, level of indirection, and possibly some naming confusion for users). The advantage of 1. is that making limited installations with just some backends is still possible.

It is also conceivable that some users will want a simple installation of Juttle with all the backends but without Outrigger and JuttleViz. For them some kind of package depending only on `juttle` and `juttle-adapter-*` would make sense.

**Comment by dmajda** [comment]
We discussed this with @bkutil and we both think that:

  * Making `outrigger` require `juttle` and `juttle-adapter-*` as hard dependencies is the way to go. We think the simplicity of this solution outweighs its limited flexibility (which really means just that some unused adapter code will get installed).
  * A package grouping `juttle` and `juttle-adapter-*` is not needed at this point. We can revisit this if there is demand from users.

**Comment by demmer** [comment]
I like this idea as well. Keeping it simple for now makes the most sense.

**Comment by demmer** [comment]
The proposed change to make outrigger depend on juttle and all the adapters was merged in https://github.com/juttle/outrigger/pull/51
