### ISSUE TITLE
adapters should loosely depend on juttle 0.x

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#145]
Proposal: Adapters should have a peer dependency on `juttle@>=0.2.0` and not on a specific minor version of juttle.

This is not an issue related to juttle itself, but rather a convention that should apply to all the adapters.

During the 0.X phase of juttle development, there will likely be many times in which we want to release a new version of juttle that bumps the minor version in ways which don't actually introduce incompatibilities with the adapters.

If we continue using the stricter version dependency on ^0.2.0, then every time we push a new version of juttle, we need to update every adapter's package.json to make it satisfy the npm dependency.

With the looser version depedency of >=0.2.0 then we can avoid the problem, at the expense of potentially causing breaking changes in the adapters if we do in fact update the juttle adapter API in a backwards-incompatible way. This seems like the right tradeoff to make until we release juttle 1.0.

Here's a checklist of which adapters have been updated. Update this checklist once a given adapter has been changed.

- [x] juttle-elastic-adapter
- [x] juttle-gmail-adapter
- [x] juttle-graphite-adapter
- [x] juttle-influx-adapter
- [x] juttle-twitter-adapter
- [x] juttle-sqlite-adapter
- [x] juttle-postgres-adapter
- [x] juttle-mysql-adapter

**Comment by dmehra** [comment]
Can we require 0.2.x and only bump juttle to 0.3 when there is a breaking change in adapters?

**Comment by dmajda** [comment]
> This seems like the right tradeoff to make until we release juttle 1.0.

It doesn’t seem like the right tradeoff to me at all.

First, I think at least at the beginning we will have more breaking releases than non-breaking releases, so updating adapter’s `package.json` will typically be associated with actual changes adapting to the breakage (or at least with determining that no adaptations are necessary).

Second, this will enable scenarios where `juttle` and some adapter will get out of sync and cause confusing errors. This will be especially bad for external developers — consider e.g. somebody extending one of our adapters who has an adapter checkout with `juttle` in `node_modules` and does `npm update`, which can given him a version that is not compatible with his checkout. And even users can run into variations of this it they won’t use Outrigger.

Third, we just enter misleading information into `package.json`. The adapter simply won’t be compatible with all future versions of Juttle.

**Comment by demmer** [comment]
> First, I think at least at the beginning we will have more breaking releases than non-breaking releases,...

I'm not sure I agree -- for instance I don't know of anything currently under way that would make it so that juttle 0.3.0 isn't compatible with all the existing adapters as written now.

> Second, this will enable scenarios where juttle and some adapter will get out of sync and cause confusing errors. ...

No doubt that is something which might occur. My instinct is that it's just not that likely given that we can still manage the development of the adapters and juttle in lock step.

> Third, we just enter misleading information into package.json...

That's also true and it doesn't make me feel good either. I would in no way endorse this for a post 1.0 release world, but by that point we would more methodically approach making potentially breaking changes.

**Comment by dmajda** [comment]
> > First, I think at least at the beginning we will have more breaking releases than non-breaking releases,...

> I'm not sure I agree -- for instance I don't know of anything currently under way that would make it so that juttle 0.3.0 isn't compatible with all the existing adapters as written now.

I know at least of two: config file changes (#133) and `pname` removal (#154)

**Comment by demmer** [comment]
> I know at least of two: config file changes (#133) and pname removal (#154)

Well actually #133 doesn't actually require a change to the adapters themselves, and for #154, a quick scan shows that many of the adapters only use the `options` and `params` arguments to initialize so the change also doesn't break anything.

However that's not really the point -- I agree that the looser dependencies are potentially problematic but there will be cases in which they're simpler. Having stricter dependencies would be, well, stricter and more likely to be correct at the expense of making releases more complicated done.

We can easily go back to that approach if the current loose model turns out to be a problem.
