### ISSUE TITLE
feature: read http option to access a nested field

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#146]
To support HTTP API endpoints that return an array of objects inside a top-level wrapper object, the http adapter should support an optional `-root` argument to read.

For example, the npm download counts API at https://api.npmjs.org/downloads/range/last-month/juttle returns an object like:
```
{
    "downloads": [
        {
            "day": "2015-12-12",
            "downloads": 3
        },
        {
            "day": "2015-12-13",
            "downloads": 1
        },
        ...
    ],
    "start": "2015-12-12",
    "end": "2016-01-10",
    "package": "juttle"
}
```

Rather than emitting a single point, it would be better to get download counts for each day as separate juttle points.

To address this, the `root` option could contain a `.` separated string that indicates the path to a field in the result object that would be treated as the root element. Note that this syntax is a subset of JSON path (e.g. https://github.com/jayway/JsonPath). 

When specified, all other options (e.g. `timeField) would then apply to the contents of the object.

**Comment by demmer** [comment]
FYI @mstemm as we discussed.

**Comment by mstemm** [comment]
This looks good, although if you also wanted to support things like array indexing in the path specification that would be a nice addition.

**Comment by demmer** [comment]
@mstemm I thought about that -- seems like a potentially useful thing to do but I'd rather just start with the simple case and then potentially enhance for the array indexing case.
