### ISSUE TITLE
Add s3 adapter

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#196]
Filing under `juttle` because there is no juttle-s3-adapter repo until we start working on this.

Rationale: while it's possible to read from public s3 buckets via `read http`, it makes sense to add explicit `read s3` (and `write s3`) to both make that use case more explicit, and enable reading/writing to private s3 buckets by supplying credentials in juttle-config.json for the new adapter.

Once this is available, we'll probably want to put sample data sets for demos/examples in s3 rather than in git.

**Comment by davidvgalbraith** [comment]
S3 stores files. Should this be its own adapter, or a `-s3` option to the `file` adapter?

**Comment by demmer** [comment]
I don't think that makes sense -- the main reason to have this as a separate adapter is to separate out the credentials and region configuration from the actual invocation of the read.

In other words a user should be able to do: `read s3 -path '/bucket/path/to/file' -format 'csv'`

Without having to specify the AWS access key or token or region.

**Comment by davidvgalbraith** [comment]
Maybe a plugin to the adapter? It just seems like a lot of the parsing and validation will be repeated.

**Comment by dmehra** [comment]
Didn't we already take out common parsing, for example to support grok on both `read file` and `read stdio`? Seems like a similar issue.

**Comment by demmer** [comment]
Yeah I was going to say that -- we already share parsing code among a bunch of the builtin adapters which we should be able to easily use for the s3 adapter as well.

**Comment by davidvgalbraith** [comment]
Great! I'll take this one, since https://github.com/juttle/juttle/pull/248 is pretty close.

**Comment by jadbox** [comment]
Might be useful to either specify in the Juttle the aws cred OR have the adapter already configured with the authentication. On one hand, you may need to change the auth account in order to access certain s3 buckets, and on the other, simplify Juttle queries when the token never needs changing (static).

**Comment by davidvgalbraith** [comment]
Thanks for the input, @jadbox! I'll be sure to include that.
