### ISSUE TITLE
use strict mode to enable ES6 classes

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#240]
Some ES6 features (class, const, let, etc) require strict mode in the current version of node.js.

Since strict mode is generally useful anyway, we should enable it globally to both make it easier to start using these features, but also to avoid the requirement for each module to have the boilerplate "use strict" at the top of each file.

A trivial way to do this in both the juttle CLI and the outrigger components would be to just use something like:
https://www.npmjs.com/package/use-strict

**Comment by demmer** [comment]
@dmajda What do you think?

**Comment by dmajda** [comment]
I totally agree with moving to the strict mode.

> A trivial way to do this in both the juttle CLI and the outrigger components would be to just use something like:
> https://www.npmjs.com/package/use-strict

Where would you do `require('use-strict')`? There are many possible entry points to the Juttle codebase, people can easily end up requiring just some subset of the files (as it often happens in tests, especially when you do just  `mocha <some-file>`), etc. I’d just bite the bullet and add `'use strict';` everywhere.

I randomly looked at React, ESLint and Express codebases, they all do it this way.

**Comment by demmer** [comment]
Yeah I thought about that and you're probably right.

We could probably end up at mostly the same result by adding `require('use-strict')` at the top of the juttle cli, outrigger, lib/compiler/index.js, lib/runtime/index.js and a few other places, but it might be hard to ensure we really cover all the entry points as you said.

It's probably better to bite the bullet and add it everywhere, and add an [eslint rule](http://eslint.org/docs/rules/strict.html) to ensure consistency.
