### ISSUE TITLE
Support `write file -format 'jsonl'` without memory limitations

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#254]
I've run up against our limits on file size and number of points for `write file`; given a 250MB input file that I was sanitizing in juttle and writing back out, I had to raise both `-limit` and `-maxFilesize` and then crashed with 
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

My understanding is that the only reason the whole file needs to fit into memory is because we're forming a valid JSON array in memory. Could we in addition support `jsonl` (json lines) format for writing, perform the write one point at a time, and not impose size limitations when in that mode? 

Also, is there some way to avoid setting up the entire thing in memory when writing out JSON?

@rlgomes your input would be welcome.

**Comment by rlgomes** [comment]
Yes there was an issue open for opening the format support for the file adapter since that would allow us to write in jsonl and csv. Will get that one done this week.
