### ISSUE TITLE
Reading a large file is slow and results in OOM

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#258]
I was running this program on an input file that's 442MB in size, and noticing that it takes a very long time (9 min) just to get to the desired `from` location in the file (which is 3/4 of the way through). Shortly after getting there and starting to process points, the program runs out of memory and quits.

```
read file -file '/tmp/kbs_metrics.json'  -from :2014-02-23T16:45:27: 
| put num = Number.fromString(String.slice(host,4,String.search(host,/\./))) 
| put skips = num%10 
| filter skips = 0 
| remove num, skips 
| write file -file '/tmp/mini_new_kbs_metrics.json' -limit 3000000
```

Even simpler the OOM can be reached with just this

```
read file -file '/tmp/kbs_metrics.json' 
| filter banana=true"
```

Github won't let me attach the data set (zipped to 30MB) but @rlgomes has it. Here is a snippet:

```
[
    {
        "name": "app.ep.client_http.kbytes_out",
        "host": "host146.samwell.jutt.le",
        "time": "2014-02-22T21:52:35.000Z",
        "kb_out": 13110.5087890625
    },
    {
        "name": "app.ep.client_http.kbytes_out",
        "host": "host605.hodor.jutt.le",
        "time": "2014-02-22T21:52:35.000Z",
        "kb_out": 1366.416015625
    },

```

**Comment by rlgomes** [comment]
Figured out the leak was due to not returning `oboe.drop` when using the oboe library to correctly free up all used memory while parsing each JSON object. Will have a PR up shortly...
