### ISSUE TITLE
Release 2016.3

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#305]
This is a tracking issue for the Juttle release 2016.3 starting on 2016-02-01. See the [wiki page](https://github.com/juttle/juttle/wiki/Releases) for details about the process.

When you release a package, check a checkbox in this list and add the released version in parens after the package name:

  * Juttle
    * [x] `juttle` ([0.4.1](https://github.com/juttle/juttle/releases/tag/v0.4.1))
  * Adapters
    * [x] `juttle-elastic-adapter` (0.4.1)
    * [x] `juttle-gmail-adapter`(no change, [0.4.2](https://github.com/juttle/juttle-gmail-adapter/releases/tag/v0.4.2))
    * [x] `juttle-graphite-adapter` ([0.3.1](https://github.com/juttle/juttle-graphite-adapter/releases/tag/v0.3.1))
    * [x] `juttle-influx-adapter` ([0.4.0](https://github.com/juttle/juttle-influx-adapter/releases/tag/v0.4.0))
    * [x] `juttle-opentsdb-adapter` ([0.1.2](https://github.com/juttle/juttle-opentsdb-adapter/releases/tag/v0.1.2))
    * [x] `juttle-sql-adapter-common` ([0.3.3](https://github.com/juttle/juttle-sql-common-adapter/releases/tag/v0.3.3))
      * [x] `juttle-mysql-adapter` ([0.3.0](https://github.com/juttle/juttle-mysql-adapter/releases/tag/v0.3.0))
      * [x] `juttle-postgres-adapter` ([0.3.1](https://github.com/juttle/juttle-postgres-adapter/releases/tag/v0.3.1))
      * [x] `juttle-sqlite-adapter` ([0.3.1](https://github.com/juttle/juttle-sqlite-adapter/releases/tag/v0.3.1))
    * [x] `juttle-twitter-adapter` ([0.2.2](https://github.com/juttle/juttle-twitter-adapter/releases/tag/v0.2.2) - no changes needed)
  * Client side
    * [x] `juttle-viz` ([0.4.2](https://github.com/juttle/juttle-viz/releases/tag/v0.4.2))
    * [x] `juttle-client-library` ([0.3.0](https://github.com/juttle/juttle-client-library/releases/tag/v0.3.0))
    * [x] `juttle-viewer` ([0.1.0](https://github.com/juttle/juttle-viewer/releases/tag/v0.1.0))
  * Engine
    * [x] `juttle-service` ([0.2.0](https://github.com/juttle/juttle-service/releases/tag/v0.2.0))
    * [x] `juttle-engine` ([0.2.0](https://github.com/juttle/juttle-engine/releases/tag/v0.2.0))
    * [x] `outrigger` (push deprecated version)

**Comment by demmer** [comment]
@juttle/developers I updated this checklist to reflect the new juttle-service and juttle-engine packages. As discussed internally, the plan is to release these instead of a new outrigger release and start guiding customers to use that instead, deprecating the existing outrigger package

Since there are references to outrigger in the juttle docs, I think we should push a 0.4.1 juttle release that points to juttle-engine instead.

**Comment by demmer** [comment]
Also I renamed this issue to avoid potential confusion -- some people thought that 3/2016 meant March 2016.

**Comment by demmer** [comment]
And I just renamed again to avoid `#` so that github wouldn't auto-link to an issue.

**Comment by demmer** [comment]
Released all the things. Phew.
