### ISSUE TITLE
Don’t allow -from equal to -to

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#322]
Currently we require `-from` <= `-to` to avoid results which would always be empty. But the case where `-from` and to `-to` are set to the same value will also always return empty points because `-to` is exclusive.

We should probably change the check to require `-from` < `-to`. At least, I can’t find a good reason why not to.

**Comment by demmer** [comment]
Yeah I agree -- that makes sense to me.

**Comment by bkutil** [comment]
I updated the time range semantics page accordingly.
