### ISSUE TITLE
NaN pops up in arity error message

### ISSUE THREAD

**Issue by bkutil** [juttle/juttle#328]
```
function f(a) { 
return a;
}
emit -limit 10 
| put a = f()
```

This correctly fails at compile-time, but the message is:
"Error: function f expects 1 to NaN arguments but was called with 0"
We should say something like "function f expects 1 argument but was called with 0"

**Comment by dmajda** [comment]
I think this should be tested in `test/runtime/specs/juttle-spec/expressions/function-call.spec.md`. I’d just:

  1. Clone the parameters testcases.
  2. Remove optional parameters in one copy and adapt (e.g. remove now irrelevant testcases).
  3. Add `(with optional parameters)` and `(without optional parameters)` suffixes to the descriptions.
