### ISSUE TITLE
CLI table columns are often too narrow

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#33]
The CLI sets column width for `view table` based on the name/value of the first field it sees, meaning it crops values in the later rows that are wider. 

The workaround is to set `-progressive=false` option, but that seems too onerous for the user; perhaps the fix is to make that the default, if we know the program is historical not live?

Simple example:

```
juttle -e "read file -file '/tmp/github_data_from_es.json' | split | reduce by name"
```
Output sets width from "name" and "type", severely trimming later values like "actor_login":
```

┌──────────┐
│ name     │
├──────────┤
│ type     │
├──────────┤
│ actor_l… │
├──────────┤
│ repo_na… │
├──────────┤
│ n_commi… │
└──────────┘
```
The data in the file is like this and we should be able to show full values like actor_login in the table:

```
[
    {
        "type": "IssuesEvent",
        "actor_login": "smarterclayton",
        "repo_name": "GoogleCloudPlatform/kubernetes",
        "time": "2015-01-04T03:03:37.000Z"
    },
    {
        "type": "ForkEvent",
        "actor_login": "miksmile",
        "repo_name": "puppetlabs/puppet",
        "time": "2015-01-04T03:18:18.000Z"
    }
]
```

**Comment by demmer** [comment]
I don't think it would be good to set progressive = false by default.

However a simple solution would be too look at all the points in the initial batch to figure out the set of fields and column widths as opposed to just the first point. This should cover most cases, but if this still isn't sufficient, we could also add a bit of delay to make sure that enough representative points have arrived.
