### ISSUE TITLE
add proper read support for time field options

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#339]
The runtime requires that in all points, the field `time` must either be a valid JuttleMoment or not present.

To support various back end adapters in handling time fields, the `parseTime` utility function should be extended to support the following options and semantics.

* `timeField` - Name of the field in the original data that, if present, is expected to contain a valid time. The default is `time`.
* `timeRenameField` - If the original data contains a field named `time`, this specifies the name of the field in the resulting juttle point that should contain a copy of the `time` field.

For any point in which the resulting 'time' field cannot be converted into a valid Juttle time, the runtime must log a warning and not process the data point.

When the timeField is not `time`, the original field should be removed from the point before emitting it to juttle.

For example, given the following data point:

```
{time: "2015-01-01T00:00:00.000Z", other: "2015-02-01T00:00:00.000Z", value: 10}
```

Then `read` with no options should produce:

```
{time: "2015-01-01T00:00:00.000Z", other: "2015-02-01T00:00:00.000Z", value: 10}
```

`read -timeField 'other'` should produce:

```
{time: "2015-02-01T00:00:00.000Z", value: 10}
```

`read -timeField 'other' -timeRenameField 'origTime'` should produce:

```
{time: "2015-02-01T00:00:00.000Z", origTime: "2015-01-01T00:00:00.000Z", value: 10}
```

Given a data point of:

```
{time: "invalid", other: "2015-02-01T00:00:00.000Z", value: "abc"}
```

Then `read` with no options should produce:

```
Warning: the time field must contain a number or a string representing time.
```

Then `read -timeField "value"` with no options should produce:

```
Warning: the time field must contain a number or a string representing time.
```

`read -timeField 'other'` should produce:

```
{time: "2015-02-01T00:00:00.000Z", value: "abc"}
```

`read -timeRenameField 'badtime'` should produce:

```
{badTime: "invalid", other: "2015-02-01T00:00:00.000Z", value: "abc"}
```

`read -timeField "other" -timeRenameField 'badtime'` should produce:

```
{badTime: "invalid", time: "2015-02-01T00:00:00.000Z", value: "abc"}
```

**Comment by go-oleg** [comment]
> Warning: the time field must contain a number or a string representing time.

or Date?

**Comment by go-oleg** [comment]
:+1: 

Is there a similar issue in the works for `-timeField` behavior in `write`?

**Comment by demmer** [comment]
> or Date?
Good point

**Comment by demmer** [comment]
> Is there a similar issue in the works for -timeField behavior in write?

No but there should be.

**Comment by VladVega** [comment]
> For example, given the following data point:
> 
> `{time: "2015-01-01T00:00:00.000Z", other: "2015-02-01T00:00:00.000Z", value: 10}`
> 
> read -timeField 'other' should produce:
> 
> `{time: "2015-02-01T00:00:00.000Z", value: 10}`

Should this case also produce a warning if there is a value for `pt.time`? Maybe `"Warning: overwriting value of time field with {{info.field}} field"`

**Comment by demmer** [comment]
Yeah -- that makes sense. Though how would the user suppress that warning?


On Fri, Feb 5, 2016 at 2:15 PM, Vlad Vega <notifications@github.com> wrote:

> For example, given the following data point:
>
> {time: "2015-01-01T00:00:00.000Z", other: "2015-02-01T00:00:00.000Z",
> value: 10}
>
> read -timeField 'other' should produce:
>
> {time: "2015-02-01T00:00:00.000Z", value: 10}
>
> Should this case also produce a warning if there is a value for pt.time?
> Maybe "Warning: overwriting value of time field with {{info.field}} field"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juttle/juttle/issues/339#issuecomment-180593868>.
>



-- 
Michael Demmer
Jut - CTO / VP Engineering
demmer@jut.io

**Comment by dmajda** [comment]
What is the status of this now that #315 is merged?

**Comment by demmer** [comment]
Closing this now that #315 is merged. If a need for `timeRenameField` comes up we can always revisit the issue.
