### ISSUE TITLE
figure out what to do about unittest taking more than 5s in travis

### ISSUE THREAD

**Issue by rlgomes** [juttle/juttle#35]
Seems a few tests sometimes get "stuck" and fail like so:

https://travis-ci.org/juttle/juttle/jobs/98344411

We should either fix the tests so they're not taking multiple seconds to begin with which puts them closer to tripping the 5s timeout on travis due to running on virtualized systems or increase the timeout to something higher to accommodate the virtualization slow down.

**Comment by dmajda** [comment]
@rlgomes Is this still relevant after #71 got in?

**Comment by rlgomes** [comment]
Yes and I simply increased the timeout to 10s for the time being and haven't seen any more random failures in travis.
