### ISSUE TITLE
`read stochastic` emits throttling warning for too many logs

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#39]
```
juttle docs/examples/backends/demo_cdn_historic.jutlle
```
used to result in:
```
{ [RuntimeError: Warning: too many logs from sea.0, throttling]
  message: 'Warning: too many logs from sea.0, throttling',
  code: 'RT-TOO-MANY-LOGS-WARNING',
  info:
   { host: 'sea.0',
     location: { filename: 'main', start: [Object], end: [Object] },
     procName: 'readx-demo' } } 'Warning: too many logs from sea.0, throttling'
```

I redid the docs example to avoid this, but without specifying a filter, I had to squeeze the time interval to 30 minutes to avoid the warning, above that it's "too many logs".

The workaround is to specify filter expressions in the read:

```
read stochastic -source 'cdn' -from :1 week ago: -to :now: -source_type 'metric'
name = 'requests' OR name = 'cpu' OR name = 'response_ms' OR name = 'disk'
```

This also avoids the big data too big issue. Stlil, it's not obvious to the user how to do that, I wish the source was generating enough data but not so much that naive use of it lands you in BDTB territory.

**Comment by demmer** [comment]
To clarify, the problematic invocation would be something like:
```
read stochastic -from :1 week ago: -to :now: | ...
```

The current code throttles at 1000 messages -- we can bump it up to 100,000 to make this less likely to occur.
