### ISSUE TITLE
Remove the “sigma” core reducer, introduce “stats.sd” in stdlib

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#390]
`sigma` (standard deviation of a batch) really belongs with its friends in `stdlib.stats`, not as a core function. Let’s relocate it. And name it `sd` or `stddev`.

(This issue was tracked as PROD-8818 internally.)

**Comment by rlgomes** [comment]
@demmer you did this with the stdev work right ? so shall we close this ?

**Comment by dmajda** [comment]
No, `stdev` is still a built-in reducer. And I think it should stay that way given that we now [optimize it at least in the Elasticsearch adapter](https://github.com/juttle/juttle-elastic-adapter/pull/114). I’ll close the issue now with the assumption this is what we want — if anyone disagrees, feel free to reopen.

(For me, this was always a borderline case and I never had a strong opinion. The issue description represents @welch’s opinion which I mechanically pulled from JIRA.)

**Comment by rlgomes** [comment]
If `stdev` is a built in then we should nuke this https://github.com/juttle/juttle/blob/master/lib/stdlib/stats.juttle#L90 right ?

**Comment by dmajda** [comment]
@rlgomes Yes.

**Comment by rlgomes** [comment]
https://github.com/juttle/juttle/pull/661 removing this duplicate implementation
