### ISSUE TITLE
Allow specifying precision with Math.{floor,round,ceil}

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#393]
Add optional `digits` argument to `Math.floor`, `Math.round`, and `Math.ceil` to allow specifying rounding precision.

(This issue was tracked as PROD-7285 internally.)

**Comment by rlgomes** [comment]
Do we want to simply apply [toPrecision](http://www.w3schools.com/jsref/jsref_toprecision.asp) after the calculation of floor,round or ceil ?

**Comment by dmajda** [comment]
The implementation Will started before open-sourcing did [something slightly more complicated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round#Decimal_rounding).

Calling `toPrecision` before/after the calculation definitely won’t work as JavaScript’s `Math.round` & co. always round to 0, destroying any more fine-grained rounding. One has to multiply, round, and divide.

**Comment by rlgomes** [comment]
@dmajda I can take this one on then and pull in that decimal rounding approach in the link you provided.

**Comment by dmajda** [comment]
@rlgomes Sure, go ahead.
