### ISSUE TITLE
Rename client sink to view in the code

### ISSUE THREAD

**Issue by mstemm** [juttle/juttle#40]
We're trying to standardize on the name "view" for the endpoint of a
program that is viewed (either in the cli as a table/text block, or in
the browser). So go through a big rename exercise to clean that up.

**Comment by dmehra** [comment]
Is this the rename `@table` -> `view table` and other visual sinks? I was under the impression we got it all done, including on juttle-viz side with @go-oleg . Or is this something else? unclear on the "endpoint of a program that is viewed".

**Comment by mstemm** [comment]
no this is changing the code to refer to views as views and not sinks or client sinks.

**Comment by demmer** [comment]
This work was completed in #115
