### ISSUE TITLE
Fix escaping in globs

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#431]
Escaping a `*` or `?` in a glob using `\`, which works e.g. in shell and Elasticsearch, doesn’t work in globs used in `filter`. For example, the following programs return one point while they shouldn’t return any (note `\` needs to be written as `\\` inside a string because of string escaping rules):

```juttle
emit -from :0: -limit 1 | put a = 'x' | filter a ~ '\\*'
```

```juttle
emit -from :0: -limit 1 | put a = 'x' | filter a ~ '\\?'
```

Strangely, what works is escaping with `*`. The following programs return no points:

```juttle
emit -from :0: -limit 1 | put a = 'x' | filter a ~ '**'
```

```juttle
emit -from :0: -limit 1 | put a = 'x' | filter a ~ '*?'
```

This is a side effect of using [gex](https://www.npmjs.com/package/gex).

(This issue was tracked as PROD-2894 internally.)

**Comment by dmajda** [comment]
@bkutil Assigning to you, should be a trivial transformation before passing the glob to gex.

**Comment by bkutil** [comment]
@dmajda: famous last words :) I'll take a look :)
