### ISSUE TITLE
read http should not dump a full error

### ISSUE THREAD

**Issue by bkutil** [juttle/juttle#465]
Entering a bogus stock identifier into the 'stock prices' demo results in the full 404 HTML page being appended into the demo (it is probably a part of the error message).

The http adapter read should guard against these errors flooding the output by replacing the message with a meaningful alternative. And/or for json, we could try parsing it first and if that fails, fallback to a pre-defined text.

**Comment by rlgomes** [comment]
If I hide the response body on failure its going to make debugging the error quite hard to say the least. Shouldn't the we not display the full error message if the message itself is larger than a certain amount ? and instead truncate it on the UI when displaying ? Otherwise I don't see how you'd figure out what the issue was if we altered/removed or truncated the returned error payload from the HTTP service you were hitting.

**Comment by bkutil** [comment]
Well, we can handle this only in the UI, or maybe we could use a generic message and assign the whole payload to `error.details`, which the UI would only log to console?

cc: @go-oleg

**Comment by go-oleg** [comment]
If the response code is well known (like a 404), I think replacing the error message with something code-specific makes sense (at the http adapter layer). Other than that, yea for long messages we could show a truncated version and have a button to expand to full message. However, I am guessing that most of the time you _do_ want to see the whole message right away so you can resolve it. Unexpected/unknown error messages should show up rarely so I think its somewhat okay if they become a bit intrusive.

**Comment by dmajda** [comment]
Error messages (the `message` property) are meant to be short, one-line strings and any UI displaying them (ours or not) will likely count on that. Putting the whole 404 response there feels like abuse which is bound to break these UIs.

I think the right solution is to throw an error with specific code (e.g. `HTTP-ERROR`), put a short message into the `message` property, and put the unparsed HTTP body into a `body` field. On the UI level, we can handle these errors specially, e.g. using an expander button/link to show the response for debugging.

What do you think?

**Comment by rlgomes** [comment]
@dmajda that makes more sense. I'll put the status message of the HTTP response (ie OK, Not Found, etc) into the message and put the current payload returned into the body field as you mentioned. That way we don't lose any information and yet the UI's don't have to worry about displaying a huge HTML payload.
