### ISSUE TITLE
error stripping locations from read / write procs

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#507]
The following command produces an opaque error:

```
# bin/juttle --mode compile -e 'read file'
Error: Cannot read property 'apply' of undefined
```

The problem comes when the location stripper is trying to walk the AST, since the node generated for the read and write procs contains a child element (the adapter name) that has no AST node type but does have a location.

At the same time, the ASTVisitor should give more helpful errors when encountering problems in the AST.

**Comment by dmajda** [comment]
> At the same time, the ASTVisitor should give more helpful errors when encountering problems in the AST.

This facility [exists](https://github.com/juttle/juttle/blob/a79ef2687c69ec99c2dde5b83e73d9d7586872d8/lib/compiler/ast-visitor.js#L5-L10) from day 1, it is just disabled by default for performance reasons.
