### ISSUE TITLE
Make “reduce -every” emit marks

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#52]
`reduce -every <x>` should be an equivalent to `batch <x> | reduce` in that it emits marks on batch boundaries. Currently it doesn’t do that.

The impact is, for example, that sinks with logic for redrawing on batch boundaries (such as `view barchart`) must be fed from a `batch | reduce` not from `reduce -every` if the redrawing is to work correctly. If the batch marks were emitted down either path, then the juttle programmer doesn't need to be aware of these special cases.

**Comment by henridf** [comment]
oh no @dmajda are you going to let that happen?! :)

**Comment by bkutil** [comment]
@henridf care to elaborate?

**Comment by henridf** [comment]
Whether or not `reduce -every` should emit marks was one of the (many) juttle design questions that kept coming up in recurring debate until it was settled (!?) that they  shouldn't.  @dmajda can probably fill you in on the history...

**Comment by dmajda** [comment]
@henridf Yes, I am going to let that happen :-)

Some of the decisions we made got revisited as the set of people influencing the language design changed. In this particular case, the discussion was philosophical — do we think of the stream as the set of points flowing through the flowgraph which are merely *viewed* as batches occasionally, or do we *really* send little table of points through (at least conceptually)? This is coupled with practical issues such as duplicating (or distributing) `-every` to procs following `reduce`, views, etc. In the end, the view that “tables are real” prevailed, at which point it made sense unify `batch | reduce` and `reduce -every` behavior.

Note this didn’t kill the plan of adding `-every` to other batch-aware procs, in fact the thinking is that `batch` should be more or less deprecated (we will keep it mostly for symmetry with `unbatch`, which we need).

**Comment by henridf** [comment]
Thanks for the context @dmajda!

**Comment by dmehra** [comment]
Will the resolution of this issue make it possible to write this program without using `batch`? It currently must use it because `sort -every` and `head -every` do not exist. The program is simply outputting top 100 links for each day.

```
read elastic -from :2009-04-01: -to :2009-05-01: link != null 
| batch :1 day:
| reduce count() by link
| sort count -desc
| head 100
```

**Comment by dmajda** [comment]
@dmehra Yes, it will be just:

```
read elastic -from :2009-04-01: -to :2009-05-01: link != null 
| reduce -every :1 day: count() by link
| sort count -desc
| head 100
```

**Comment by bkutil** [comment]
Closing as fixed.
