### ISSUE TITLE
Q: program deactivation logic

### ISSUE THREAD

**Issue by bkutil** [juttle/juttle#528]
The tests currently delay the deactivation using `deactivateAfter` parameter, which shuts down the program after a certain period of time has passed.

If I get things correctly, the program should deactivate either after all reads/writes finish, or when the juttle process receives a signal.

How does the deactivation logic currently work?

**Comment by bkutil** [comment]
cc: @davidvgalbraith @demmer

**Comment by demmer** [comment]
I think the correct behavior is implemented in #532.

**Comment by bkutil** [comment]
Makes sense - should/does the same logic apply when the program is not exercised via tests?

**Comment by demmer** [comment]
When outside of tests, deactivate should happen when the user hits control-c or pushes a stop button or something like that.
