### ISSUE TITLE
Remove the “sourceType” property

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#54]
The sourceType property of Juttle sources is currently used only to distinguish sources and other procs. Once we introduce a base class for sources, it won’t be needed. Let’s get rid of it to make the API cleaner.

Depends on "Add a base class for sources" (done).

- [x] don't use `sourceType` to detect sources
- [x] remove `sourceType` from built-in sources
- [x] remove `sourceType` from sources in backends

**Comment by bkutil** [comment]
Ok, this should be complete - lets wait for the PRs to be merged, then close this one.
