### ISSUE TITLE
rename the sigma reducer to stddev

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#541]
It would be clearer and more consistent to use `stddev` as the reducer name that calculates standard deviation instead of `sigma`.

Noted in the discussion on #540.

**Comment by davidvgalbraith** [comment]
The [cool](https://docs.python.org/3/library/statistics.html#statistics.stdev) [kids](https://support.office.com/en-us/article/STDEV-function-51fecaaa-231e-4bbb-9230-33650a72c9b0) call it just `stdev`.
