### ISSUE TITLE
Support nested points in Juttle

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#55]
- [x] correctly handle nested points when grouping
- [x] correctly handle nested points in `sort`
- [x] correctly handle nested points in all backends
- [x] correctly handle nested points in views
- [x] correctly handle nested points in all remaining procs

**Comment by dmehra** [comment]
Details for each task:

### correctly handle nested points when grouping
Support correct grouping by fields containing arrays or objects. This means that:
- Group keys should be tested for equality using the relation defined in values.js.
- Group keys which are arrays or objects should not be stringified when emitted as part of emitted points.

### correctly handle nested points in sort
Support sorting by fields containing arrays or objects. This means field values should be compared using relations defined in {{ops.js}}.

### correctly handle nested points in all backends

### correctly handle nested points in views
Make sure that views handle points with fields containing arrays or objects correctly. More specifically, this means:
- Field values should be stringified using the function defined in values.js.
- Wherever a field value is used for equality testing, comparison, sorting, etc. it should be either handled using functions defined in values.js/ops.js or unhandled value types should be rejected with understandable error message. This includes e.g. values passed in -keyField of incoming points.

### correctly handle nested points in all remaining procs
In no proc should a field containing array or object cause an internal error or incorrect behavior. In general, values should be handled using functions defined in values.js/ops.js (which may throw type errors in certain situations — this is fine). Where this is impossible, unhandled value types should be rejected with understandable error message.
This is a "catch-all" issue for all cases not covered by the above.

**Comment by dmajda** [comment]
> @bkutil does this mean we will support writes of nested points too?

Yes, where possible.

---

I think it makes sense to split this issue according to the tasks (they are themselves pretty big) and maybe keep this one for overall tracking (as an “epic” in scrum terminology). Leaving this to @bkutil.

**Comment by bkutil** [comment]
- [ ] nested point with array value
- [ ] nested point with list of objects value (that's supported right?)
- [ ] reduce by two non-scalar fields
- [ ] other "by" invocations such as head by
- [ ] sort on non-scalar field
- [ ] join on non-scalar field
- [ ] pluck non-scalar field
- [ ] unique on non-scalar field
- [ ] the four above called without parameters on data containing non-scalar

**Comment by bkutil** [comment]
Handle nested points in core views:

- [x] file
- [x] text
- [x] table

Views for juttle-viz are tracked in a separate issue: https://github.com/juttle/juttle-viz/issues/17

**Comment by bkutil** [comment]
Handle nested points in adapters - ensure that nested points get serialized and written out correctly, or that appropriate error is raised when the adapter does not support that.
- [ ] influx
- [ ] elastic
- [ ] gmail
- [ ] graphite
- [ ] sql
- [x] ~~twitter~~ (no write support)

**Comment by bkutil** [comment]
Check nested points in remaining procs:

- [ ] skip
- [ ] sequence
- [ ] split
- [ ] remove
- [ ] keep

**Comment by bkutil** [comment]
The remaining work to be done is tracked in the juttle viz repo: https://github.com/juttle/juttle-viz/issues/17, closing.
