### ISSUE TITLE
Generalize filter expressions

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#57]
Remove filter expression checks, which enables more expressive filter expressions in filter (ones which include field-to-field comparisons, function execution on fields, etc.).

Implementation plan (see [below](https://github.com/juttle/juttle/issues/57#issuecomment-174889819) for details):

  * [x] Move all structural filter checks from the semantic pass into `FilterChecker`
  * [x] Extend `FilterJSCompiler` to handle dynamic filters
  * [x] Split `FilterChecker` into `StaticFilterChecker` and `DynamicFilterChecker`
  * [x] Switch `filter` and `sequence` to dynamic filters

**Comment by dmajda** [comment]
So the current idea is that we will have two kinds of filters in Juttle:

  * **Static filters.** These will be similar to filters we have now. They will allow only comparison of fields against each other and against compile-time values. Optionally they will also allow FTS. The intent is to translate them into backend queries.

  * **Dynamic filters.** These will be the “generalized filters” as originally envisioned. They will allow all kinds of streaming expressions like computing functions over fields, the `*` unary operator, etc. They won’t allow FTS. The intent is to translate them into JavaScript code.

Procs like `filter` will allow dynamic filters. Adapters will be able to chose which kind of filter they allow (note this means the kind of a filter used in `read` won’t be known statically). Typically, big data adapters will allow only static filters (translating them into backend queries) while small data adapters will allow dynamic filters (translating them into JavaScript which they will run on incoming points).

---

Now the implementation plan:

  1. **Move all structural filter checks from the semantic pass into `FilterChecker`.** This means all filters will pass through the semantic pass like any other expression.
  2. **Extend `FilterJSCompiler` to handle dynamic filters.** This mostly means adding support for compiling streaming expressions.
  3. **Split `FilterChecker` into `StaticFilterChecker` and `DynamicFilterChecker`.** The former will do the same thing as `FilterChecker` today, the latter will probably just check for FTS.
  4. **Switch `filter` and `sequence` to dynamic filters.** The adapters will still use static filters.

The next step (subject of some follow-up issue) is allowing adapters to opt-in into dynamic filters and generally make their dealing with filters easier (I’m thinking about having some declarative way to specify what is allowed in each adapter’s filter). There is an API to be discussed and designed here.
