### ISSUE TITLE
Runaway program detector errors have no location information

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#572]
Example:

```
$ bin/juttle -e 'read file -file "xxx" -from :beginning: -to :end: | tail 1'
Error: Not starting program as it would run forever with no output. Add a -to option to read?
```

**Comment by rlgomes** [comment]
@dmajda I'll have a look at this one as I could swear I made sure to pass down the location information.

**Comment by dmehra** [comment]
By the way, the helpful message "add -to option to read?" is not so helpful when -to is already supplied, can we distinguish between the two runaway cases and emit different error messages?

**Comment by rlgomes** [comment]
@dmehra that can be easily distinguished so le tme open an issue to rework the messages there and then you can review my bad english ;)

**Comment by rlgomes** [comment]
@dmehra that message is so irrelevant at this point given the nature of how a read without a `-to` no longer reads forever... so yeah, legacy messaging
