### ISSUE TITLE
Complete core library modules: String, Array, Object

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#58]
Core library modules such as `String`, `Array`, and `Object` are mostly ad-hoc and incomplete. Finish them.

Specifically for Array, @dmajda proposed:

Implement the `Array` module with basic array-manipulating functions. A good start may be just wrapping [functions defined on arrays in ECMAScript 5.1](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.3).

We may also want to add `Array.zip` - the lack of it today requires the user to write juttle reducers like this:

```
reducer zip(a, b) {
  // return an array of pairs [[a0, b0], [a1, b1], ...]
  var A = [], B = [];
  function update() {
    A = *a; B = *b;
  }
  function zip_tail(A, B, C, n) {
    if (A[n] == null) { 
      return C;
    }
    C[n] = [A[n], B[n]];
    return zip_tail(A, B, C, n+1);
  }
  function result() {
    return zip_tail(A, B, [], 0);
  }
}
```

to be used like this:

```
 | put px = percentile(x, [0, .5, 1]), py = percentile(y, [0, .5, 1])
 | put qq = zip(px, py)
 | split qq
```

**Comment by dmajda** [comment]
The high-level idea for this issue (which was lost by copying the original not-that-useful description) is to complete Juttle’s core library — more specifically, the `String`, `Array`, and `Object` modules where we are missing useful functionality. Some time ago I and Henri decided not to reinvent the wheel but look at what `String`, `Array`, and `Object` objects in ES5 have and more or less copy that into Juttle core modules. This approach has some advantages:

  1. The functionality will be familiar to our users who know JavaScript.
  2. We don’t have to invent our own core library (with all the inevitable bikeshedding).
  3. We already started on this course, so it’s natural to continue.
  4. The implementation will be simple.

The biggest disadvantage is that JavaScript core functionality is sometimes crappy.

---

Looking quickly at the [ES 5.1 spec](http://www.ecma-international.org/ecma-262/5.1/) I think it makes sense for Juttle to steal the following:

  * `Array.toString`
  * `Array.concat` (probably make it work just for arrays)
  * `Array.join`
  * `Array.pop`
  * `Array.push`
  * `Array.reverse`
  * `Array.shift`
  * `Array.slice`
  * `Array.sort` (use Juttle value comparison, not JavaScript’s crapy behavior here)
  * `Array.splice`
  * `Array.unshift`
  * `Array.length`
  * `Array.indexOf`
  * `Array.lastIndexOf`
  * `Object.keys` (also add `Object.values`, which is not in ES5)
  * `Object.toString`
  * `String.fromCharCode`
  * `String.toString`
  * `String.charAt`
  * `String.charCodeAt`
  * `String.concat`
  * `String.indexOf`
  * `String.lastIndexOf`
  * `String.length`
  * `String.match`
  * `String.replace`
  * `String.search`
  * `String.slice`
  * `String.split`
  * `String.substring` (also add `String.substr`, which is not in ES5)
  * `String.toLowerCase`
  * `String.toUpperCase`
  * `String.trim`

Notes:

  1. Some of these functions we already have. Great.
  2. I omitted all the locale-related functions (`toLocaleString`, etc.) — I don’t think we need them and they are underspecified.
  3. In case of arrays I omitted things which require first-class functions (`forEech`, `map`, etc.) — we don’t have first-class functions in Juttle.
  4. I’d avoid ES6 stuff for now, some may not be implementable in ES5 environment (but I didn’t look too deeply).

**Comment by dmajda** [comment]
Reopening, the new additions also need to be documented.
