### ISSUE TITLE
shouldn't try to load adapters that aren't needed

### ISSUE THREAD

**Issue by henridf** [juttle/juttle#83]
Juttle crashes when I run `juttle -e "emit -limit 2 | put message='hello'"` because it can't find an adapter that's listed in my config.json (but not currently installed).

It would be nicer if it only tried to lookup adapter(s) that are actually needed in the script that is being run.

**Comment by henridf** [comment]
s/search for/try to load/ in title because now that I've fixed the es-elasticsearch-adapter, I'm realizing that the spurious loading also slows things down pretty badly. 

on my host, loading the es adapter appears to take around 300-400ms. skipping that when it's not needed would be nice. 

(nitpicky? maybe. but right now, `sqlite3 db "select * from my_table limit 10"` runs instantaneously (4ms), while the corresponding juttle takes about 1.5s, which feels really slow on the command line).

**Comment by dmajda** [comment]
Makes sense to me.

**Comment by demmer** [comment]
I agree as well. I can take a swag at this.
