### ISSUE TITLE
error stringifying undefined

### ISSUE THREAD

**Issue by henridf** [juttle/juttle#90]
```
$ time juttle -e "read sqlite -timeField 'my_time_field' -table 'my_table' |  head 1 | view table"   
[2016-01-03 21:52:06.832] [INFO] juttle-adapter - loaded elastic
[2016-01-03 21:52:07.283] [INFO] juttle-adapter - loaded sqlite
Cannot read property 'toString' of undefined [TypeError: Cannot read property 'toString' of undefined]
└────────────────────────────────┴─────────────────────┴───────────────┴───────────────┘
```

my guess is that `pt.my_time_field = undefined` happens somewhere in the source, and `my_time_field` is iterated on as part of `Object.keys()` somewhere in the sink.

**Comment by dmajda** [comment]
@henridf Your intuition was correct, [I took this to `juttle-sql-adapter-common`](https://github.com/juttle/juttle-sql-adapter-common/issues/8).
